import Head from 'next/head'
import Image from 'next/image'
import AppLayout from '../components/AppLayout'
import Button from '../components/Button'
import GitHub from '../components/Icons/Github'
import profilePic from '../public/2.png'
import { colors } from '../styles/theme'
import { loginWithGihub, onAuthStateChanged } from '../firebase/client'
import { useEffect, useState } from 'react'
import Avatar from '../components/Avatar'
import { useRouter } from 'next/router'
import useUser, { USER_STATES } from '../hooks/useUser'




export default function Home() {
  const user = useUser()
  const router = useRouter();



  useEffect(() => {
    user && router.replace('/home')
  }, [user])

  const handleClick = () => {
    loginWithGihub().then(user => {
      const { avatar, username, url } = user;
      setUser(user);
      console.log(user)
    })
  }


  return (
    <>
      <Head>
        <title>Tweet Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout >
        <section>
          <Image width="100" height="100" src={profilePic} alt="logo" />
          <h1>TweetDev</h1>
          <h2>Talk about development<br /> with developers</h2>
          <div>
            {
              user === USER_STATES.NOT_LOGGED && <Button onClick={handleClick}>
                <GitHub fill="#fff" width={24} height={24} />
                Login with Github
              </Button>
            }
            {
              user === USER_STATES.NOT_KNOW && <span>Loading...</span>}


          </div>
        </section>
      </AppLayout>

      <style jsx>
        {`

          section {
            display: grid;
            place-content: center;
            height: 100%;
            place-items: center;
          }

          div {
            margin-top: 16px;
          }

          h1 {
            color: ${colors.primary};
            font-weight: 800;
            margin-bottom: 16px;
          }
          h2 {
            color: ${colors.secondary}
            font-size: 21px;
            margin: 0;
          }
        `}
      </style>

    </>
  )
}

